import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Todo from "../app/components/todo"
import NavBar from "./components/navBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    {/*
    <nav style={{ width: "100%" , background: "teal", fontSize: "30px" , display:"flex", justifyContent: "center" , alignItems: "center"}}>
      <Link style={{ margin:"8px" }} href="/">Home</Link>
      <Link style={{ margin:"8px" }} href="/articles">Articles</Link>
      <Link style={{ margin:"8px" }} href="/posts">Posts</Link>
    </nav>
    */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
